version: '3'

services:

  postgres:
    build:
      context: ./postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rsmarket:
    build: rsmarket
    env_file:
      - ./env/rsmarket-docker.env
    environment:
      - DATA_DIR=/opt/rsdata
    volumes:
      - ./rsmarket/rsmarket/data:/opt/rsdata
    depends_on:
      postgres:
        condition: service_healthy
    command: "log -f -n"

# vi: sw=2 ts=2
