version: '3.1'

services:

  postgres:
    build:
      context: ./postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres-vars.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    env_file:
      - ./env/pgadmin-vars.env

  rsmarket:
    build: rsmarket
    env_file:
      - ./env/rsmarket-vars.env
    environment:
      - DATA_DIR=/opt/rsdata
    volumes:
      - ./rsmarket/rsmarket/data:/opt/rsdata
    depends_on:
      postgres:
        condition: service_healthy
    command: "log -f -n"

volumes:
  postgres-data:
  pgadmin:

# vi: sw=2 ts=2
